// Copyright (c) 2014-2017 Coin Sciences Ltd
// MultiChain code distributed under the GPLv3 license, see COPYING file.

#ifndef KAICOINVERSION_H
#define	KAICOINVERSION_H

#define KAICOIN_VERSION_MAJOR     1
#define KAICOIN_VERSION_MINOR     0
#define KAICOIN_VERSION_REVISION  0
#define KAICOIN_VERSION_STAGE     2
#define KAICOIN_VERSION_BUILD     2

#define KAICOIN_PROTOCOL_VERSION 10008
#define KAICOIN_PROTOCOL_SUPPORTED "10004 - 10008, 20001"


#ifndef STRINGIZE
#define STRINGIZE(X) DO_STRINGIZE(X)
#endif

#ifndef DO_STRINGIZE
#define DO_STRINGIZE(X) #X
#endif

#define KAICOIN_BUILD_DESC_WITH_SUFFIX(maj, min, rev, build, suffix) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-" DO_STRINGIZE(suffix)

#define KAICOIN_BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build) \
    DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build)


#define KAICOIN_BUILD_DESC "1.0 beta 2"
#define KAICOIN_BUILD_DESC_NUMERIC 10000202


#ifndef KAICOIN_BUILD_DESC
#ifdef BUILD_SUFFIX
#define KAICOIN_BUILD_DESC KAICOIN_BUILD_DESC_WITH_SUFFIX(KAICOIN_VERSION_MAJOR, KAICOIN_VERSION_MINOR, KAICOIN_VERSION_REVISION, KAICOIN_VERSION_BUILD, BUILD_SUFFIX)
#else
#define KAICOIN_BUILD_DESC KAICOIN_BUILD_DESC_FROM_UNKNOWN(KAICOIN_VERSION_MAJOR, KAICOIN_VERSION_MINOR, KAICOIN_VERSION_REVISION, KAICOIN_VERSION_BUILD)
#endif
#endif

#define KAICOIN_FULL_DESC(build, protocol) \
    "build " build " protocol " DO_STRINGIZE(protocol)


#ifndef KAICOIN_FULL_VERSION
#define KAICOIN_FULL_VERSION KAICOIN_FULL_DESC(KAICOIN_BUILD_DESC, KAICOIN_PROTOCOL_VERSION)
#endif


#define KAICOIN_VERSION_CODE_PROTOCOL_THIS              0
#define KAICOIN_VERSION_CODE_PROTOCOL_MIN               1
#define KAICOIN_VERSION_CODE_PROTOCOL_MIN_DOWNGRADE     2
#define KAICOIN_VERSION_CODE_PROTOCOL_MIN_NO_DOWNGRADE  3
#define KAICOIN_VERSION_CODE_PROTOCOL_FOR_RELEVANCE     4
#define KAICOIN_VERSION_CODE_BUILD                     16
#define KAICOIN_VERSION_CODE_MIN_VALID               1000

#endif	/* KAICOINVERSION_H */

